swiftmailer:
    url: '%env(MAILER_URL)%'


    #spool: { type: 'memory' }
#
#    transport:            sendmail
#    username:             sylvie@hevie.fr
#    password:             onOrange4201*
#    host:                 auth.smtp.1and1.fr
#    port:                 587
#    encryption:           ssl
#    auth_mode:            ~
#    spool:
#        type:                 file
#        path:                 '%kernel.cache_dir%/swiftmailer/spool'
#    sender_address:       sylvie@hevie.fr
#    antiflood:
#        threshold:            99
#        sleep:                0
#    delivery_addresses:   []
#    disable_delivery:     ~
#    logging:              '%kernel.debug%'

