index:
    path: /
    controller: App\Controller\HomeController::homeDisplay

formTransaction:
    path: /transaction
    controller: App\Controller\TransactionController::addTransaction

cardNumber:
    path: /cardNumber
    controller: App\Controller\PaymentController::cardNumber

validPayment:
    path: /validPayment
    controller: App\Controller\PaymentController::validPayment

validation:
    path: /validation
    controller: App\Controller\PaymentController::sendSpoolAction
